#!/usr/bin/env python3
import os,sys
sys.path.append(os.getcwd()+"/.lib/")
sys.path.append(os.getcwd()+"/.src/")

import logging
import random
import argparse
from datetime import datetime
from _main_ import osintEye, args
from colors import red,green,white,reset


if __name__ == '__main__':
	start = datetime.now()
	if args.verbose:
		logging.basicConfig(format=f"{white}[{green}*{white}] %(message)s{reset}",level=logging.DEBUG)
	while True:
		try:
			osintEye(args).main()
			if args.verbose:
				exit(f"\n{white}[{green}-{white}] osint{red}Eye{white} stopped in {green}{datetime.now()-start}{white} seconds.{reset}")
			break
			
		except KeyboardInterrupt:
			if args.verbose:
				exit(f"\n{white}[{red}x{white}] osint{red}Eye{white} interrupted with {red}Ctrl{white}+{red}C{reset}")
			break
			
		except Exception as e:
			if args.verbose:
				print(f"{white}[{red}!{white}] An error occured: {red}{e}{reset}")
				print(f"{white}[{green}+{white}] Retrying...{reset}")
