#!/usr/bin/env python3

from src.main import *
from datetime import datetime
from lib.colors import red,green,white,reset


if __name__ == '__main__':
	while True:
		try:
			osintEye(args).main()
			break
			
		except KeyboardInterrupt:
			if args.verbose:
				print(f"\n{white}[{red}x{white}] Interrupted with {red}Ctrl{white}+{red}C{reset}")
				break
			break
			
		except ImportError:
			if args.verbose:
				print(f"{white}[{red}!{white}] Error: {red}{e}{reset}")
				
	if args.verbose:
		exit(f"{white}[{green}-{white}] Finished in {green}{datetime.now()-start_time}{white} seconds.{reset}")
